version: '3.8'

networks:
  network1:
    driver: bridge
    ipam:
      config:
        - subnet: 172.16.1.0/24 
    name: network1

services:
  postgres:
    image: postgres:alpine3.18
    environment:
      POSTGRES_USER: ${PG_USER}
      POSTGRES_PASSWORD: ${PG_PASSWORD}
      POSTGRES_DB: ${PG_BASE}
      PGSSLMODE: ${PG_SSL_MODE}
    ports:
      - ${PG_EXTERNAL_PORT}:${PG_PORT}
    networks:
      - network1
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 30s
      timeout: 10s
      retries: 5

  redis:
    image: redis:latest
    environment:
      REDIS_PASSWORD: ""
      REDIS_PORT: ${REDIS_PORT}
      REDIS_DATABASE: ${REDIS_DB}
    ports:
      - ${REDIS_EXTERNAL_PORT}:${REDIS_PORT}
    networks:
      - network1
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 30s
      timeout: 10s
      retries: 5

  web:
    build: .
    ports:
      - ${SERVER_EXTERNAL_PORT}:${SERVER_PORT}
    depends_on:
      postgres:
        condition: service_healthy
      redis:
         condition: service_healthy
    networks:
      - network1

